name: CI

on:
  push:

jobs:
  slurm-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux/arm64]
        target: [slurmctld, slurmd, slurmdbd, slurmrestd, sackd, slurm]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push
        run: |
          docker buildx build --file Dockerfile --target ${{ matrix.target }} \
            -t ghcr.io/${{ github.repository_owner }}/${{ matrix.target }}:${{ github.ref_name }} \
            -t ghcr.io/${{ github.repository_owner }}/${{ matrix.target }}:latest \
            --platform ${{ matrix.platform }} --push .
