name: CI

on:
  push:

jobs:
  bake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push
        uses: docker/bake-action@v6
        with:
          source: .
          push: true
          set: |
            *.tags=ghcr.io/${{ github.repository_owner }}/app:latest
